### ISSUE TITLE
Integration with arkworks-rs

### ISSUE THREAD

**Issue by weikengchen** [ingonyama-zk/cloud-ZK#1]
The arkworks-rs 0.4.0 may be coming in this month.

Are you interested in the discussion of integration? We can have some formal discussion in one or two weeks... but the idea is to make this a plug-in alternative as a backend for arkworks-rs. 

The API would be the one that needs to most attention---since 0.5.0 may be two years later. In the worst case, a fork with patches-crates.io provides a drop-in replacement.

At first, maybe we will do it in the same machine (i.e., local), and then we can think about a distributed manner.

**Comment by omershlo** [comment]
That will be awesome! let's discuss over telegram

**Comment by weikengchen** [comment]
Just to update that the current plan is to make it a wrapper of `ark-bls12-377`, like `ark-bls12-377h`, which implements a special version of G1Projective that uses a different MSM algorithm compared with the default SW one. 

This minimizes the changes and is also transparent to other parts of the system.

**Comment by weikengchen** [comment]
If you are thinking about something like ingo-bls12-377 I think it is also fine---you do have Rust engineers right?

**Comment by omershlo** [comment]
The wrapper idea sounds good! thanks for the update!

**Comment by weikengchen** [comment]
Let us consider it closed as https://twitter.com/Ingo_zk/status/1595521373275066368

Great work!
